version: "3"

services:

  grafana:
    image: grafana/grafana:7.3.6
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasource-influxdb.yaml:/etc/grafana/provisioning/datasources/influxdb.yaml:ro

  influxdb:
    image: influxdb:1.8.3-alpine
    environment:
      - INFLUXDB_DB=testdb
      - INFLUXDB_ADMIN_USER=influxdb_user
      - INFLUXDB_USER_PASSWORD=influxdb-super-password
    ports:
      - "2003:2003"
      - "8086:8086"
    volumes:
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
